version: "3.3"
services:
  frontend:
    image: daryamakauchyk/kupipodariday-frontend:latest
    ports:
      - 8081:80
    restart: on-failure 
    healthcheck:
      test: "wget -nv -t1 --spider 'http://localhost:8081/'"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  backend:
    image: daryamakauchyk/kupipodariday-backend:latest
    ports:
      - 4000:3000
    restart: on-failure 
    links: 
      - database
    depends_on:
      - database
    environment:
      DATABASE_URL: database
      DATABASE_PORT: 5432
    healthcheck:
      test: "wget -nv -t1 --spider 'http://localhost:4000/'"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  database:
    image: postgres:14
    container_name: kupipodariday
    ports: 
      - 5432:5432
    restart: on-failure 
    volumes: 
      - /var/lib/docker/volumes/db-kupipodariday/_data
    environment:
      POSTGRES_HOST: db-kupipodariday
      POSTGRES_PORT: 5432
      POSTGRES_PGDATA: /var/lib/docker/volumes/db-kupipodariday/_data
      POSTGRES_USER: student
      POSTGRES_DB: kupipodariday
      POSTGRES_PASSWORD: student