# backend
# frontend
# database

version: "3.9"
services:
  frontend:
    image: "daryamakauchyk/kupipodariday-frontend:nginx:1.23.1-alpine"
    ports:
      - "3000:8081"
  backend:
    image: "daryamakauchyk/kupipodariday-backend:node16-alpine"
    ports:
      - "3000:4000"
  database:
    image: "postgres:12"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_PGDATA: /var/lib/docker/volumes/db-kupipodariday/_data
      POSTGRES_USER: student
      JWT_SECRET: some-extra-super-secret-key-that-noone-will-ever-know-about
      POSTGRES_DB: kupipodariday
      POSTGRES_PASSWORD: student

