version: "3.3"
services:
  frontend:
    container_name: frontend
    image: daryamakauchyk/kupipodariday-frontend:latest
    build: ./frontend
    ports:
      - 8081:80
    restart: on-failure 
  backend:
    container_name: backend
    image: daryamakauchyk/kupipodariday-backend:latest
    build: ./backend
    ports:
      - 4000:3000
    restart: on-failure 
    links: 
      - database
    depends_on:
      - database
    env_file:
      - ./.env
  database:
    image: postgres:14
    container_name: kupipodariday
    ports: 
      - 5432:5432
    restart: on-failure 
    volumes: 
      - /var/lib/docker/volumes/db-kupipodariday/_data
    env_file:
      - ./.env