# backend
# frontend
# database

version: "3.9"
services:
  frontend:
    image: daryamakauchyk/kupipodariday-frontend:latest
    ports:
      - 8081:80
  backend:
    image: daryamakauchyk/kupipodariday-backend:latest
    ports:
      - 4000:3000
    links: 
      - database
    depends_on:
      - database
    environment:
      - DATABASE_URL=database
      - DATABASE_PORT=5432
  database:
    image: postgres:14
    container_name: kupipodariday
    ports: 
      - 5432:5432
    volumes: 
      - /var/lib/docker/volumes/db-kupipodariday/_data
    environment:
      POSTGRES_HOST: db-kupipodariday
      POSTGRES_PORT: 5432
      POSTGRES_PGDATA: /var/lib/docker/volumes/db-kupipodariday/_data
      POSTGRES_USER: student
      POSTGRES_DB: kupipodariday
      POSTGRES_PASSWORD: student