# backend
# frontend
# database

version: "3.9"
services:
  frontend:
    image: "daryamakauchyk/kupipodariday-frontend:nginx:1.23.1-alpine"
    ports:
      - "3000:8081"
  backend:
    image: "daryamakauchyk/kupipodariday-backend:node16-alpine"
    ports:
      - "3000:4000"
  database:
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: secretpassword 
